[package]
name = "zsstwebr"
version = "0.0.0"
authors = ["Erik Zscheile <erik.zscheile@gmail.com>"]
edition = "2018"

[dependencies]
aho-corasick = "0.7"
clap = "2.33"
chrono = { version = "0.4", features = ["serde"] }
readfilez = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
walkdir = "2.3.1"
